;;;; module-for-expand.import.scm - GENERATED BY CHICKEN 5.0.0 -*- Scheme -*-

(##sys#register-compiled-module
  'module-for-expand
  'module-for-expand
  (scheme#list)
  '((the-func . module-for-expand#the-func))
  (scheme#list)
  (scheme#list))

;; END OF FILE
